### ISSUE TITLE
Menu buttons renaming when click on contact

### ISSUE THREAD

**Issue by XylotrupesGideon** [BuildTheEarth/website-frontend#10]
When you click on "contacts" the menu buttons get renamed for some reason

![image](https://user-images.githubusercontent.com/31574542/211616921-36b76d91-49da-4274-8e20-069eec877b04.png)

the same happens in the footer:

![image](https://user-images.githubusercontent.com/31574542/211620563-cca9f7a7-7887-47e8-8567-cfcbbbaf7334.png)

**Comment by Nudelsuppe42** [comment]
Fixed with https://github.com/BuildTheEarth/website-frontend/commit/8102a95c3b64a8a96dd2684cc7615f397eab0659
