### ISSUE TITLE
images for Build teams in the "Build Teams" page

### ISSUE THREAD

**Issue by XylotrupesGideon** [BuildTheEarth/website-frontend#14]
It would be cool if the Build teams could already showcase a building or area in the build team page. so that the BT log is on the left and a build is featured on the right for example.

![image](https://user-images.githubusercontent.com/31574542/211619350-eb3c8cae-f356-4aaa-89fc-92ca3bdd6b26.png)

**Comment by Nudelsuppe42** [comment]
It would look a bit weird on a large scale with 10+ Teams on one page each with their own logo and images
