### ISSUE TITLE
Cookie notice doesn't resize properly on mobile

### ISSUE THREAD

**Issue by Xesau** [BuildTheEarth/website-frontend#52]
![Image](https://github.com/BuildTheEarth/website-frontend/assets/7915413/126c2c9e-dc56-4758-ae7b-1bfc104e2cd0)

**Comment by Nudelsuppe42** [comment]
https://github.com/BuildTheEarth/website-frontend/commit/fba277f8b277da499ea1deec20481c45f01a82ef
