### ISSUE TITLE
Black overlay on the image on the main site is smaller than the image behind it

### ISSUE THREAD

**Issue by 20Alexanderxx** [BuildTheEarth/website-frontend#9]
![Screenshot_20230110_133320_Chrome](https://user-images.githubusercontent.com/89459209/211557214-a599850e-837d-4e0a-980e-430749f4ab61.jpg)

Visible if scrolled a bit down

**Comment by Nudelsuppe42** [comment]
Fixed with https://github.com/BuildTheEarth/website-frontend/commit/d55e8a95702511dfbd438163f4d4887c0c53ffd8
